/**
 * 🚨 此文件由 CloudEnableTool 自动生成，请勿修改！
 * This file is auto-generated by CloudEnableTool. Do not edit manually!
 */

import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export function getSupabaseUrl(): string {
  return `${(window as any).MEOO_CONFIG?.meoo_app_access_url || window.location.origin}/sb-api`;
}

export const supabaseUrl = getSupabaseUrl();
// meoo-cloud 尚未初始化，使用 supabase client 请先调用 meoo-cli cloud init
export const supabaseAnonKey = '<meoo-cloud-anon-key-placeholder>';

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
});
